# Generated by Django 3.1.5 on 2022-07-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_group_name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=10)),
                ('under', models.CharField(max_length=100)),
                ('should_quantity_of_items_be_added', models.CharField(max_length=5)),
            ],
        ),
    ]
