# Generated by Django 3.1.5 on 2022-07-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_category_name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=10)),
                ('under', models.CharField(max_length=100)),
            ],
        ),
    ]
