# Generated by Django 3.1.5 on 2022-07-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0002_stock_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=10)),
                ('under', models.CharField(max_length=100)),
            ],
        ),
    ]
