# Generated by Django 3.1.5 on 2022-07-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='companypricelevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_level_name', models.CharField(max_length=100)),
            ],
        ),
    ]
