# Generated by Django 3.1.5 on 2022-07-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0004_companypricelevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('formal_name', models.CharField(max_length=50)),
                ('number_of_decimal_places', models.IntegerField()),
                ('first_unit', models.CharField(max_length=50)),
                ('conversion', models.IntegerField()),
                ('second_unit', models.CharField(max_length=50)),
            ],
        ),
    ]
