# Generated by Django 3.1.5 on 2022-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0006_auto_20220722_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='conversion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='first_unit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='number_of_decimal_places',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
